### ISSUE TITLE
Power?

### ISSUE THREAD

**Issue by thanone2** [joojoooo/pico360#1]
How did you power the pico and esp32? Also, can you give a picture of what the controller looks like from the outside?

**Comment by joojoooo** [comment]
The USB Y cable provides power to the Pico, the Vout of Pico (5V) is connected with the ESP32 5V, GND are connected. What do you mean how the controller looks like?

**Comment by joojoooo** [comment]
This is the cable I'm using, it provides power to the Pico and to the USB A Female port: USB OTG Y Splitter cable. It's not required but makes connecting easier.
<img src="https://github.com/joojoooo/Bluetooth-Xbox360-Controller/assets/95318316/63f4c862-b841-4bec-8008-389e483704a2" width=40% height=40%>

**Comment by joojoooo** [comment]
@thanone2 I made a video: https://youtu.be/J1_S5z4gUoo

**Comment by thanone2** [comment]
ok, thanks! and btw when i said "how the controller looks like". I meant, did you put the components in a case? or are they dangling out the back? But I now realize (after seeing the video) that it's its own thing.

**Comment by joojoooo** [comment]
> ok, thanks! and btw when i said "how the controller looks like". I meant, did you put the components in a case? or are they dangling out the back? But I now realize (after seeing the video) that it's its own thing.

No way the wireless receiver fits inside the controller, it's easier to keep everything external. Let me know if you need help.

**Comment by thanone2** [comment]
would you mind taking a picture of how it fits inside?

**Comment by joojoooo** [comment]
> would you mind taking a picture of how it fits inside?

What do you want to put inside of what? I still don't understand. You want to put the ESP and Pico inside the Xbox 360 controller?

**Comment by thanone2** [comment]
> > ok, thanks! and btw when i said "how the controller looks like". I meant, did you put the components in a case? or are they dangling out the back? But I now realize (after seeing the video) that it's its own thing.
> 
> No way the wireless receiver fits inside the controller, it's easier to keep everything external. Let me know if you need help.

yes and, sorry it seemed that you implied it fit inside the controller.

**Comment by joojoooo** [comment]
No I said the opposite. Can you exaplain what you're trying to do? The wireless receiver is too big. Maybe if you remove it from the plastic enclosure and solder the USB wires directly to Pico GPIO instead of using the OTG splitter cable then you can probably fit everything on the back of the controller, in place of the battery. But then how do you power everything ? battery won't fit anymore so you need a cable providing power to the controller, which defeats the whole point of it being wireless.

![20240202_224233](https://github.com/joojoooo/Bluetooth-Xbox360-Controller/assets/95318316/c78e76a4-4acd-486d-9095-f55e5cd6a565)
 
![20240202_224249](https://github.com/joojoooo/Bluetooth-Xbox360-Controller/assets/95318316/312eea24-cc8f-4251-a0bc-279bff8d97c2)

![20240202_225617](https://github.com/joojoooo/Bluetooth-Xbox360-Controller/assets/95318316/79b1af1f-65f2-4194-bfef-32414f95701e)

![20240202_225603](https://github.com/joojoooo/Bluetooth-Xbox360-Controller/assets/95318316/6cbe5703-5d0d-433b-b634-8b5725b82768)

**Comment by thanone2** [comment]
Oh, ok sorry for my stupidity, I was trying to make my wired controller wireless, and I see what you were saying, my brain distorted what I was reading, sorry for bothering you with pictures.

**Comment by thanone2** [comment]
btw will the code still work if I wired the controller directly to the esp32?

**Comment by joojoooo** [comment]
> btw will the code still work if I wired the controller directly to the esp32?

the esp32 has no usb host support, usb is wired to the pico. Yes it will work for the wired xbox 360 controller too with a small change to the code

**Comment by thanone2** [comment]
> > btw will the code still work if I wired the controller directly to the esp32?
> 
> the esp32 has no usb host support, usb is wired to the pico. Yes it will work for the wired xbox 360 controller too with a small change to the code

nice, Thank you for this tremendous help!

**Comment by thanone2** [comment]
sorry, but quick question, do I need the raspberry pi if I'm directly wiring the usb to the esp32?

**Comment by thanone2** [comment]
> > btw will the code still work if I wired the controller directly to the esp32?
> 
> the esp32 has no usb host support, usb is wired to the pico. Yes it will work for the wired xbox 360 controller too with a small change to the code

will i still need the raspberry pi pico?

**Comment by joojoooo** [comment]
obviously yes, the esp isn't able to communicate with an usb full speed device like the controller or the receiver. That's why I used a Pico in the first place

**Comment by thanone2** [comment]
> obviously yes, the esp isn't able to communicate with an usb full speed device like the controller or the receiver. That's why I used a Pico in the first place

ok, thanks!
